name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.5.0'

    - name: Install dependencies
      run: npm install

    - name: Check formatting with Prettier
      run: npm run format -- --check

    - name: Run ESLint
      run: npm run lint

    - name: Run tests with Jest
      run: npm test